### ISSUE TITLE
MouseRegion onHover and onExit are not triggered while awaiting an async function

### ISSUE THREAD

**Issue by JaviBonilla** [Cretezy/flutter_cursor#2]
Thanks for this package. I have noticed that the cursor is not restored while awaiting an async function, apparently because the onHover and onExit MouseRegion events are not triggered.

I attach a recording. Any idea how to solve this?

<img src="https://user-images.githubusercontent.com/20316179/82763298-f7a50180-9e06-11ea-9b38-c5f4a60cc1ee.gif " width="150" />

**Comment by Cretezy** [comment]
This is a good report, thanks. I'm not sure how this be fixed, I'll see what I can do!

**Comment by JaviBonilla** [comment]
Hi @Cretezy 

It turned out it is working now. I was changing the widget (icon button) while loading (circular progress indicator) and this last widget was not wrapped with HoverCursor, so the cursor didn't changed when exiting, so this issue can be closed.

**Comment by Cretezy** [comment]
Ah makes sense! Will close :)
