### ISSUE TITLE
MouseRegion onExit is not triggered when then MouseRegion disappears

### ISSUE THREAD

**Issue by JaviBonilla** [Cretezy/flutter_cursor#3]
This may happen when a button is clicked to open another page.

This is by design, [have a look here](https://github.com/flutter/flutter/issues/44957). 

I tried implementing this in **HoverCursor** but the app does not compile.

```
void dipose() {
    body.style.cursor = exitCursor;
    super.dispose();
}
```

Any idea about how to solve this?

**Comment by Cretezy** [comment]
This is a good point, I will fix shortly.

**Comment by Cretezy** [comment]
Version v0.1.3 is out with a fix for this. Let me know if it's good!

**Comment by JaviBonilla** [comment]
Thanks @Cretezy,

I tested and it is not working (the cursor is never shown) in master branch, I don't know if this has something to do with my configuration.
